### ISSUE TITLE
Let user set the magneticod port

### ISSUE THREAD

**Issue by JanWelker** [boramalper/magnetico#1]
Magneticod uses a random UDP port to listen for incoming connections. This is not practical if one uses a firewall. One would like to configure a static port to be able to configure the same port on the firewall.

Cheers,
Jan

**Comment by itdaniher** [comment]
Ran into this issue, thanks for the fix. I suppose UnPlug-n-Pray (UPnP) would be another solution, for those times where both a firewall and UPnP are in play.

**Comment by boramalper** [comment]
@JanWelker Thanks a lot for the feedback! I'll hopefully implement it through command line arguments until this weekend.

**Comment by boramalper** [comment]
This is implemented long ago but I forgot to close the issue. =)
