### ISSUE TITLE
Bandwidth usage

### ISSUE THREAD

**Issue by Programming4life** [boramalper/magnetico#10]
What's the bandwidth usage like?

**Comment by itdaniher** [comment]
20-30GB/day, limited by CPU.

**Comment by Programming4life** [comment]
Holy ****! Is there a bandwidth limit option?

**Comment by J-Bird-Medic** [comment]
Well that excludes me completely. At least until a portable option is available.
Home is rural, satelite or cellular only.

**Comment by itdaniher** [comment]
I'd strongly recommend (by virtue of the design of this program) to get a cheap VPS and dedicate it magnetico. Anything bottom tier will suffice.

**Comment by boramalper** [comment]
I am planning to add an option limit bandwidth usage, **BUT** you should not run this at home. Use a cheap VPS as @itdaniher suggested, or a seedbox if you have, but using this at home might give you some headache in future. **magneticod** sends hundreds to thousands of requests while crawling the network, and your home connection might be marked as spam or your ISP might accuse you for misuse (or whatever).

**Comment by boramalper** [comment]
@Programming4life Practically you are not torrenting, but technically you are using its protocols and participating in the network... Personally, I would give it a try and see if I receive a complaint. It's hard to say anything else at this point.

**Comment by Programming4life** [comment]
@boramalper Okay, I'll give it a try. Thanks.

**Comment by Programming4life** [comment]
@itdaniher "Anything bottom tier will suffice." Apparently not, Keep getting alot of Belated Tick warnings, and nothing is being added. Are you using a vps if so who is the provider?

**Comment by itdaniher** [comment]
@Programming4life linode.com and vultr.com are both known to work.

**Comment by Jiezhi** [comment]
bandwagonhost shutdown my vps after running this project just 1 min or so...

is it like a DDOS?

**Comment by Jiezhi** [comment]
A sad story, I tried running it again, no more than 30s, my VPS get this:
**Reason**:	Network abuse: (D)DoS attack
**More details**:	Server was involved in a (D)DoS attack. Since DoS attacks affect other customers on our network, and with accordance with our Terms of Service, this service was automatically suspended.

**Comment by itdaniher** [comment]
Wow. Email them, explain it's a UDP bandwidth-intensive application. They should be ashamed....

**Comment by itdaniher** [comment]
![image](https://cloud.githubusercontent.com/assets/22683/25075517/5d889aa8-22cb-11e7-85b9-f45db416e185.png)
Running magneticod non-stop yielded 743055 torrents before I ran out of my 1TB bandwidth.

**Comment by boramalper** [comment]
Closing the issue as v0.8.1 has parameters to allow the CPU and bandwidth usage to be controlled.

Feel free to open a _new_ issue if you still have any problems with it. =)
