### ISSUE TITLE
Feature Request: Remove Search Results- Magneticow

### ISSUE THREAD

**Issue by Maverik44** [boramalper/magnetico#100]
Lets say I am running a search for "linux" but I don't want to display results with the word "ubuntu".

"linux -Ubuntu"

This would be helpful.

**Comment by qoole** [comment]
Already does.

**Comment by Maverik44** [comment]
![ubuntu](https://user-images.githubusercontent.com/29182516/27205865-bc185bc2-51f0-11e7-833e-378af81c6855.PNG)

Its not working for me.. All of the Ubuntu results should be removed.

**Comment by qoole** [comment]
I have just tested it and it seems to work as expected for me. Are you running an old version?

![image](https://user-images.githubusercontent.com/2862661/27225668-2516ae24-5293-11e7-9e18-f8932fee9736.png)


![image](https://user-images.githubusercontent.com/2862661/27225626-f9d7437c-5292-11e7-9238-dc67a39e2c89.png)

![image](https://user-images.githubusercontent.com/2862661/27225650-0dbb9762-5293-11e7-8920-9ad05825f1b7.png)

**Comment by boramalper** [comment]
Try `linux NOT ubuntu` ("not" has to be fully capitalized). See [Set Operations Using The Enhanced Query Syntax](https://sqlite.org/fts3.html) for more details.

I'll document them as well. =)

**Comment by Maverik44** [comment]
boramalper: "linux NOT ubuntu" worked perfect.

Thank you for the "Set Operations Using The Enhanced Query Syntax for more details." link was super helpful. = - )
![linux](https://user-images.githubusercontent.com/29182516/27240461-01dfe674-5292-11e7-9a3e-ea4badde23e7.png)

**Comment by boramalper** [comment]
You're welcome!

**Comment by boramalper** [comment]
Since now it's also documented in [the docs](https://github.com/boramalper/magnetico/tree/master/magneticow), I'm closing the issue. =)
