### ISSUE TITLE
Performance on __on_FIND_NODE_response and __decode_nodes

### ISSUE THREAD

**Issue by Glandos** [boramalper/magnetico#102]
Hi,
I run magneticod 0.6 at home (ADSL, 18Mb/s down 1Mb/s up), and it seems that the routing table of the SybilNode is full really quickly.
However, `__decode_nodes` is called prior to this filtering (see https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/dht.py#L163).
It seems that performing tests to see how many nodes can be decoded (if any), and give that hint to `__decode_nodes` should really boost performance. On my setup, `__decode_nodes` calls (including children) eats between 4% and 7% of the total CPU time.

As an example, I add this two lines:
```
        if len(self._routing_table) >= self.__n_max_neighbours:
            return
```
just before the call to `__decode_nodes` and the result is clear. On 118103 calls to `__on_FIND_NODE_response`, there is now only 40546 calls to `__decode_nodes`. Before this, the call number was on par for each function.
It could also be reduced because a lot of times, the new nodes are not totally read, so it is not necessary to decode all nodes.

I should have time to make a patch for this, but not now, and I didn't want to lose this thoughts.

**Comment by boramalper** [comment]
Hey, that's one great catch\*, congrats and many thanks!

*: and shameful for me.

**Comment by Glandos** [comment]
A quick commit is already a good thanks 👍
