### ISSUE TITLE
Feature Request: Add No Authentication flag - Magneticow

### ISSUE THREAD

**Issue by Maverik44** [boramalper/magnetico#103]
When running Magneticow add support for no username and password.

magneticow  --port 8080 --user username_1 password_1 --user username_2 password_2

vs

magneticow  --port 8080 --no authentication

**Comment by scriptzteam** [comment]
You can get inspired how to do iz quick n dirty ^^

https://github.com/boramalper/magnetico/pull/14/commits/3809cdfd1743f561ce57affd3c9c271d07c61530

P.S.: short after i saw magnetico was user only access i wanted to remove it, so get that like 1min of brain work and login require removed :D

**Comment by mweinelt** [comment]
Was resolved in recent commits, can be closed.
