### ISSUE TITLE
Database abstraction

### ISSUE THREAD

**Issue by Glandos** [boramalper/magnetico#108]
Following the discussion in #106 we are all expecting to see if magnetico could use another database than SQLite.

First of all, be aware of the [guidelines](https://github.com/boramalper/magnetico/blob/master/CONTRIBUTING.rst#kinds-of-contributions) : 

> Ease of installation, and of use are our primary concerns

Then, remember that SQLite is awesome as a single client database. For example, my database is 2.7GB large (and I'm sure it's not the largest), and requests are still answered in a timely fashion for indexed columns.

But the discussion of switching to another storage was motivated by those use cases:

- Run multiple magneticod with the same database
- Is relational database the best fit for our use case?

Let's talk.

**Comment by Glandos** [comment]
Personally, I'm quite fine with SQLite, its ease of installation and its performance, but I would also appreciate the move to an abstraction that can enable magnetico to use other SQL databases such as PostgreSQL or MySQL.

Using a NoSQL database can be tempting, but I'm not sure that it is a good idea. Using a relational database can give a lot of search features for magneticow.

**Comment by ad-m** [comment]
@Glandos , non-relational databases, especially documentary database has special search feature. See for example Elasticsearch, MongoDB. In this aspect document databases offers out-of-the-box a lot more fg. faceting, stemming, . In our database structure there is no relation between torrents, so there is no reason to use relation database. There is only multiple documents. 

I do not insist on using them, I present facts.

**Comment by Glandos** [comment]
This is true. However, setting up an ElasticSearch database is not easy. This is just an example, there maybe better choices for document databases, and I'm clearly not an expert of them. I've only tried [UnQLite](https://www.unqlite.org/), but it has slightly less performance than a fine-tuned SQLite for a simple Key/Value storage, and since it was far less popular, I've dropped it.

**Comment by boramalper** [comment]
Hi!

> * Run multiple magneticod with the same database

I don't think that you need to switch to another database for this. SQLite handles multiple processes quite well, as evidenced by **magneticod** and **magneticow** running at the same time. Though some changes need to be made in **magneticod** (to prevent issues like #97 when running multiple process), I don't think that SQLite would be a problem.

Even if you, let's say, discover half a million torrents a day, it means 6 insert operations per second, which is within the limits of SQLite.

> * Is relational database the best fit for our use case?

I don't know. There were 3 main reasons which made me go for SQLite:

1. It was a built-in library, with seamless integration with the language, and well-tested (both the library itself and its Python bindings). I eliminated all options which required you to **install** a database server, which often meant root access or a complicated installation process & configuration.
   * Also full-text search support, built-in.
2. I was a bit more familiar with relational databases than non-relational ones.

----

I am totally fine with offering users options to choose whatever suits their needs best, but currently that requires a huge effort, both on **magneticod** and **magneticow** with very little return in my opinion (as the difference is unnoticeable for most of the cases).

Let me know if anyone is interested in this task, I would be happy to collaborate. Until then I'll focus on implementing some more features such as scraping seeder/leecher counts, DHT infohash indexing etc. =)

**P.S.:** I think the discussion would become more relevant when we start discussing more "centralized" hubs and how to make them possible. In that case, extensibility and performance would be greater and more actual concerns. See #65.
**P.S.:** I think we should discuss this once again

**Comment by yellowiscool** [comment]
Using ElasticSearch would improve the search engine though. And it's very easy to setup, 3 lines in the existing docker-compose file should do it.

**Comment by ad-m** [comment]
@yellowiscool , not everyone use docker-compose.

**Comment by yellowiscool** [comment]
Deploying a database is not difficult without Docker anyway. But many projects that used to be tiresome to deploy now provide docker containers and docker-compose files. I don't think a database deployment should limit the search capacities.

**Comment by boramalper** [comment]
Closing the issue since with Go rewrite, I have written an abstract database controller (see [`pkg/persistence`](https://github.com/boramalper/magnetico/tree/v0.8.1/pkg/persistence)), so anyone who is up for the task can develop an abstraction for whatever database(s) they want.

I know that there is a PR pending for Postgres (#164), but **magnetico** is still moving fairly fast, and **database is a liability**. I wouldn't like to tell people that we suddenly dropped support, and they are now somehow left with no way to use their data. I'd happily accept such changes from a maintainer, but one-time contributions are best left to future where things stabilise a bit more.

#197 can make the initiative more dare-able as we would at least offer people a way to export (and import back) their data if a contributor decides to drop support for a database.

**Comment by jangrewe** [comment]
I would also vote in favor of a complete database abstraction layer, as opposed to **only** Postgres support. That way people could continue using the SQLite database, if they wish to.
