### ISSUE TITLE
Huge drop in locating torrents

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#112]
With v4 I was locating about 8-9k torrents a day, however, since v5 and now v6, I am seeing about 1-2k only.  Nothing else has changed on my end hardware wise.  I grabbed v6 the day it was updated but none of the changes since that day.  I am honestly not sure how to do an update to get the latest bleeding edge file changes.

**Comment by scriptzteam** [comment]
We are fine here :D

https://dht.bittor.ch/stats

```
["Day 1", 18693],["Day 2", 15283],["Day 3", 19162],["Day 4", 23763],["Day 5", 18722],["Day 6", 22178],["Day 7", 24662],["Day 8", 21609],["Day 9", 25657],["Day 10", 32187],["Day 11", 36086],["Day 12", 35334],["Day 13", 30505],["Day 14", 32422],["Day 15", 30189],["Day 16", 28462],["Day 17", 28492],["Day 18", 24673],["Day 19", 27019],["Day 20", 33726],["Day 21", 33093],["Day 22", 27002],["Day 23", 33873],["Day 24", 34471],["Day 25", 27038],["Day 26", 31581],["Day 27", 22360],      ]);```

**Comment by blimeybloke** [comment]
That is odd.  May I ask what kind of server you have?  I am using kimsufi but not the lowest server.  Are you running v6? I am wondering if DB corruption is happening on my end and if I should do a full reinstall.  I never saw those kinds of numbers though but maybe its my server.

**Comment by blimeybloke** [comment]
Solved my own issue.  It was UFW that was slowing everything down.  Since it is private for a few friends and their family of my inner circle, I locked it down with UFW.  That firewall caused things to be very slow.  I am already at 26k in about 4 hours since the change was made.
