### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by guppy42** [boramalper/magnetico#114]
if performing a blank search the first many pages of results cannot be searched manually.

eg. there is a magnet for "Ubuntu 16.04 LTS.iso"

searching for "iso" only yields

"ubuntu-11.04-alternate-i386.iso"

**Comment by guppy42** [comment]
I figured it out:
It seems that searching for anything other than blank is only working for magnets found since last starting magneticow


I'd say that's a pretty big bug.

**Comment by Maverik44** [comment]
So I ran into this one. How many torrents has it found? "torrents available" on the front page

The software saves in something like groups of 10. 
So if you don't have port forward enabled for magneticod.
The result is slow torrents maybe 10 per day vs 100's per second.

**Comment by guppy42** [comment]
It found around 10k per hour, I'll try to search for something on page 20 later but I'm sure the result will be the same

**Comment by boramalper** [comment]
Sorry I couldn't understand the problem quite well so I'll try to rephrase it in my own words:

You claim that magneticow returns torrents, on a **non-empty** search, only if they are discovered **after** magneticow has been already started. Can you confirm this?

**Comment by guppy42** [comment]
Yes

**Comment by guppy42** [comment]
re-read your comment. No!

The problem is this.

The torrents that are discovered can only be found via an empty search, after restarting they can also be found via a non-empty search. But torrents found after restarting can the again only be found via empty searching.

I'll make a video to show it off its still not clear

**Comment by mweinelt** [comment]
Is this probably related to the multiple database files and only the primary one being queried on searches? After restart the cached torrents are written back into that, so they are searchable after restart, but new torrents land in the cache file again.

**Comment by boramalper** [comment]
This should be fixed now. =)
