### ISSUE TITLE
[Recommendation] Hosting

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#115]
This is not a bug but a question for those of you who are much more knowledgeable than most about server hosting.  I am running my test area on ovh but am not sure I am maxing out what I need to.  Can anyone give a recommendation for a decent hosting place?

**Comment by boramalper** [comment]
Hey @blimeybloke, sorry for the belated reply. Indeed I've been busy with some other important projects as well and couldn't pay attention to **magnetico** that it deserves.

Nonetheless, I use the cheapest Linode instance and it's been working quite well for me. I also heard good things about DigitalOcean so the choice really comes down to what you expect from a VPS. For me the chief criteria was the price, as I never really felt the need of a VPS, but needed one for testing **magnetico**. =)

**Comment by ad-m** [comment]
I think the basic criterion should be bandwidth limit. For many providers bandwidth limit of 2TB is not so much for magnetico.

I use Time4VPS (extra cheap storage VPS; torrent accepted if no comply) without issues. I have OVH instance with TOR relay-node which make +10TB/month.

I suggest install ``vnstat`` for long-term monitoring bandwidth limits.
