### ISSUE TITLE
Only localhost available for magneticow

### ISSUE THREAD

**Issue by Jaska8** [boramalper/magnetico#117]
Hi.

I couldn't find any options for magneticow listening specific address as it only allows to connect throught localhost, though this is not a problem with ssh tunneling but there's no point for the auth either.

I'm unning it inside Freebsd Jail. Also does port forwarding benefit magneticod? or does magneticod has upnp built in for port forwarding? is port randomly selected when no arguments are passed to the magneticod? (address shows as INFO      SybliNode is launched on ('0.0.0.0', 0)!)

**Comment by ad-m** [comment]
@Jaska8 , there is no way in magneticow to select listening address. There is ```magneticow --port 8090``` for listening port.

There is no UPNP support in magneticod (see #81). Port forwarding is crucial for magneticod speed (see #11). Port of mangneticod is randomly selected when no argument are passed.

**Comment by pcamelo** [comment]
@Jaska8 later will create a PR to solve the listening address issue, it's fairly easy to do as I already did it in the code locally. For the general user it makes sense to provide this option.

**Comment by mweinelt** [comment]
Both `--host` and `--no-auth` are available since a bit, making this issue obsolete.

**Comment by boramalper** [comment]
@mweinelt Thanks for the heads up!
