### ISSUE TITLE
Refactoring magneticod

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#118]
Hallo! I'm starting a heavy refactoring in **magneticod** to separate the protocol (*e.g.* Kademlia DHT, BitTorrent Peer Protocol, etc.) and the service (*e.g.* SybilNode, DisposablePeer) and while being at it, the transport and the encoding as well. **Why?** you might ask:

- I, personally, feel frustrated even to start working on the code-base as it becomes increasingly complex. Often I need to refer to multiple places to see what a single line or block of code meant to do and the amount of new bugs introduced at each new version also evidences this.
  - Separating and isolating different functionality would also allow us to write unit (and integration) tests so that we can be sure in the future that we are not breaking anyone's workflow. So that we can get out of the *pre-alpha* stage and gain wide-spread use.
- Adding new features, such as DHT Indexing and Scraping (seeder and leech counts) depends on the same protocols that we already use, but since the protocol logic is embedded into the service logic, we cannot implement them easily without introducing duplicate functionality.

We might reasonably expect some loss in performance as there will be slightly more levels of redirection and some things would be implemented more generally rather than being optimized for a very specific use case, but at the end, we will be able to implement some crucial features (such as those I mentioned afore) and assure that **magneticod** (and **magnetico**) will survive the future. =)

**Comment by Glandos** [comment]
The loss of performance can be minimal. And I'm sure that in can be compensated by implementing [BEP-0051](http://www.bittorrent.org/beps/bep_0051.html), since it would enable magneticod to retrieve much more infohashes at once.

**Comment by yae2** [comment]
Do any clients implement BEP-51?

**Comment by boramalper** [comment]
@yae2 I don't know, will see... =)

**Comment by boramalper** [comment]
Instead of a refactoring we went for a full-rewrite (with all its pros and cons...) so this issue can be closed. =)
