### ISSUE TITLE
Magenticod | Console / ssh freeze

### ISSUE THREAD

**Issue by BillVeusees** [boramalper/magnetico#123]
Hi,

I set up magneticod on a raspberry pi 2, and it works with no error (at least none showed).

The thing is when magneticod is running, my ssh session bugs after a short while (few minutes). I cannot input anything and i have to kill my terminal and log again into a new ssh session.

I can log in normally reattach my screen session and/or do some other things for a few minutes before my inputs get frozen again.

Tested on both python 3.6.2 and 3.5.4
System is installed on external hard drive (it is not flash card related)
Magneticod launched in a screen session as per instructions.
Memory available accounts for 300 to 500 Mo
CPU usage from the mageticod process shows ~ 20 to 30 %

I also tried to nice the process to 19 but it did not change a thing

Have you any idea of what may cause this strange behaviour ?

Thanks

**Comment by scriptzteam** [comment]
Seriously? :D On raspberry pi 2, dont get me wrong i know you are able to get it running but then dont ask why it freeze :D out of ram? out of cpu (if thats callable cpu whats inside raspberry xD ) ? again dont get me wrong i love raspberry and i am happy owner of few of them, but you will need more "power" i think, get a real server ;)

**Comment by BillVeusees** [comment]
I appreciate your points but I think you did not understand me. My rpi2 does does not run out of memory (half of it is used at Max) nor CPU. The freeze is an input freeze if it happens while running top for example, top Co to he's running and does not show any spike in CPU/memory usage.

On your rpi2 concerns, My other rpi2 has been running qbittorent, sickrage watcher an ftp server and http server at the same time with no trouble for 2 years so your opinion may be a bit hard...

**Comment by boramalper** [comment]
Hey @BillVeusees! Since you said the problem is not the CPU or memory usage, I am afraid it might be due to excessive number of requests (= packages) that **magneticod** sends and receives. I think a rate-limiter might solve your problem. I personally don't know how to set it up, but @mweinelt on [our gitter channel](https://gitter.im/magnetico-dev/magnetico-dev) did it himself:

> hi, I wanted to say thanks for this software
>
>crawled ~60k torrents in ~18h
>
>put the crawler into a network namespace, limited it to 2 Mbit/s through `tc`
>
>seems to be working well

**Comment by BillVeusees** [comment]
@boramalper thanks for your answer I will try to look into it !
