### ISSUE TITLE
Allow anonymous access to magneticow

### ISSUE THREAD

**Issue by mweinelt** [boramalper/magnetico#125]
If run on private networks basic-auth shouldn't be necessary, especially since deeplinking to `http://user:pass@host:port` is frowned upon by browers like chrome:

> [Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.

**Comment by scriptzteam** [comment]
That was the first thing i removed myself when i FIRST run magneticow -> https://github.com/boramalper/magnetico/pull/14/files

then i recoded whole frontend with php :D
