### ISSUE TITLE
Save torrent file

### ISSUE THREAD

**Issue by ArjLover** [boramalper/magnetico#129]
Is it possible to create torrent file when magnetico fetch meta?

**Comment by boramalper** [comment]
It is not impossible *per se*, but we don't feature it. Since storing the torrent file, alongside the metadata we keep, would increase the storage costs for no immediate benefit so we choose what fields do matter to us, save them, and discard the rest. Hope this answers your question. =)

**Comment by ArjLover** [comment]
maybe it possible to do like command-line option?

**Comment by boramalper** [comment]
To save it in the database?

**Comment by ArjLover** [comment]
To database - not good idea. Simple use file system. Like
/torrents/ABCD/ABCD.......info_hash
or
/torrents/AB/CD/ABCD.......info_hash

**Comment by Glandos** [comment]
@ArjLover I collected more than 2 millions hash in one month, using a small ADSL line. My database file is more than 8 GB. And I did some pause in the harvesting, because I was testing magneticod on the same server.
Storing files as-is is NOT a good idea, it will put too many pressure of the filesystem.

**Comment by boramalper** [comment]
@ArjLover I want to be honest with you, I don't think that we will implement what you suggest *ever*. First, as I said, I cannot see any benefit of storing the torrent files; indeed, what you'll be storing is the [info dictionary of the torrent file](https://en.wikipedia.org/wiki/Torrent_file#File_structure) (but that's also a valid torrent file). Second, even if we decide to store info dictionary of the torrent files, it won't be in the file system, but will be always in a database. A database offers much stronger guarantees with regards to consistency, and (of course) much better tools to query the data.

As a side node, I used to have 5 million torrents in my database, and it was around 19 GB. And this number is without the full-text search table, which we currently generate on **magneticow** startup...
