### ISSUE TITLE
congestion

### ISSUE THREAD

**Issue by ArjLover** [boramalper/magnetico#134]
Log of magnetico full of this message:

WARNING   Max. number of neighbours are < 200 and there is still congestion! (check your network connection if this message recurs)

It dedicated server with 1Gbit/s connection. Ubuntu 16.04. Maybe needs some tuning network subsystem by sysctl? What the real reason for this warning?

**Comment by mweinelt** [comment]
You are running into this function, that handles several exceptions that are indicators for a slow down request through the kernel.
https://github.com/boramalper/magnetico/blob/57d466a666c68fa10cc0269897a05eae5ccf4a8a/magneticod/magneticod/dht.py#L80-L104

Maybe your net.core.rmem_{max,default} values are very small? Or you're conntracking the connections and have unusually small conntrack_max? Hard to say.

**Comment by ArjLover** [comment]
I already tune all of this

# sysctl  net.core.rmem_default
net.core.rmem_default = 212992
# sysctl  net.core.wmem_default
net.core.wmem_default = 212992
# sysctl  net.core.wmem_max
net.core.wmem_max = 31457280
# sysctl  net.core.rmem_max
net.core.rmem_max = 31457280
sysctl net.nf_conntrack_max
net.nf_conntrack_max = 262144

And it happens sometimes without reason. Yesterday magnetico use 10Mbits/s and all be ok, today only 5 and a lot of message about  congestion. No another activity now on this server...

What I should edit to print the exception?

**Comment by mweinelt** [comment]
after line 80 add (properley indented)
```
print(exc)
```

**Comment by ArjLover** [comment]
ok. I try. And another question, 1024 - is it hard limit for fetch task in asyncio? Never see it more than 1024. Or it again about OS tuning?

**Comment by ArjLover** [comment]
Many messages 
[Errno 1] Operation not permitted

**Comment by boramalper** [comment]
Hey @ArjLover! Did you try step 7 in [**magneticod** installation instructions](https://github.com/boramalper/magnetico/blob/master/magneticod/README.rst#instructions)? I think it might solve your problems, as it solved mine. =)

**Comment by Glandos** [comment]
You can also check first with: 
```
> cat /proc/net/nf_conntrack | wc -l
303
```
If your number is really high, then it will help.

**Comment by ArjLover** [comment]
Now I have permanent problem with one server. I just reboot it, run magnetico and in first minute receive the error!

2017-07-28 13:54:27,537  INFO      SybliNode is launched on ('0.0.0.0', 6061)!
2017-07-28 13:54:46,621  ERROR     SybilNode error.
PermissionError: [Errno 1] Operation not permitted

what wrong? How I can debug it?

**Comment by ad-m** [comment]
@ ArjLover, enable magnetico in debug mode. Do you can use ``strace``?

**Comment by ArjLover** [comment]
Solved. It was iptables - some rules block all traffic for some networks...
