### ISSUE TITLE
Asyncio tasks limited?

### ISSUE THREAD

**Issue by ArjLover** [boramalper/magnetico#136]
When magnetico already working long time I see in log the same maximum count of tasks

2017-07-29 13:22:21,918  DEBUG     fetch metadata task count: 1008
2017-07-29 13:22:21,918  DEBUG     asyncio task count: 2020

Already several hours the same count. +-2. Is it maximun of asyncio? Or I can tune it?
And all time "asyncio task count" 2 time more than fetch. Looks strange...

**Comment by ArjLover** [comment]
Any ideas?

**Comment by boramalper** [comment]
Should disappear / be fixed by the next version as **magneticod** is going through a massive change. =)

**Comment by boramalper** [comment]
Not applicable anymore, closing the issue.
