### ISSUE TITLE
Error starting magneticow

### ISSUE THREAD

**Issue by enusri** [boramalper/magnetico#138]
Please dont go too technical on me, newb here. I installed magneticow by using "pip3 install magnetcow --user" . then how should i start 'magneticow.py' file is in my user roaming folder C drive. When i use any command that starts with magnteicow, its displays its not an internal or external command. Please help.

Thanks in advance.

**Comment by boramalper** [comment]
Hey!

Can you please give the latest version a try and see how it goes?

**Comment by Musickiller** [comment]
well, I've done the same as @enusri and got error:
```
import gevent.wsgi
ModuleNotFoundError: No module named 'gevent.wsgi'
```
OS: Windows 10
Python 3.8, also tried on 3.7

**Comment by Musickiller** [comment]
Fixed by changing all gevent.wsgi to gevent.pywsgi in the main file. However I've hit another problem for now...
