### ISSUE TITLE
Magneticod slows down on Python 3.5.4

### ISSUE THREAD

**Issue by fastesol** [boramalper/magnetico#148]
I've been struggling - for the last 3 days - identifying the actual problem of slowing down the magneticod. and I just noticed that my Python was updated from 3.5.3 to 3.5.4 and magneticod crawler slows down 200 time. that it just crawl 2 or maximum 3 torrents per minute (not sure where it stuck)

Previous stats were 25K per hour with the default settings in `constant.py`

NOTE: I'm using CentOS 7.x

**Comment by CaptainConsternant** [comment]
I can relate, after upgrading to python 3.6 from 3.5.2 I went from 500 over the weekend to 500 over 10 minutes...

**Comment by fastesol** [comment]
well, in my case, it was the firewall that create problems. I just disabled it and the speed boosted again.
