### ISSUE TITLE
Question about new rewrite

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#151]
Will we be able to use our existing collection or will we have to start from scratch?
Cheers

**Comment by scriptzteam** [comment]
Seems like a GO is a BIIIG update :)

And also I think yeah we can use it no need to start from scratch

Check this line(s):

https://github.com/boramalper/magnetico/blob/828e4691da9b03db1b57865fcfeba4560b1ac7f8/src/magneticod/persistence/database.go#L337

P.S.: Seems like Go rewrite will have Seed & Leech count and also readme "storage"

**Comment by boramalper** [comment]
You will be able t use your existing collection. =)
