### ISSUE TITLE
NOT ISSUE - Addon

### ISSUE THREAD

**Issue by blimeybloke** [boramalper/magnetico#153]
I figured I would add my fix for a situation I had.  I ran out of HD space for the DB due to it being stored by default in the root.

Here is what I did, use caution as this worked for me but it may not work for you:

mkdir /home/magneticod
cd /root/.local/share/magneticod/
mv * /home/magneticod/
cd /root/.local/share/
rm -rf magneticod
ln -s /root/.local/share/magneticod /home/magneticod

I copied the db files and then made a symlink

This was before:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G   18G  213M  99% /
devtmpfs        7.9G     0  7.9G   0% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           7.9G   15M  7.9G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/md3        1.8T   68M  1.7T   1% /home

This was after:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  1.5G   17G   9% /
devtmpfs        7.9G     0  7.9G   0% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           7.9G   15M  7.9G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/md3        1.8T   17G  1.7T   1% /home

**Comment by boramalper** [comment]
Thanks for your contribution, though I'm not sure why you created a symlink. The `--database` command line argument (in go-rewrite version, which I presume what you use) is precisely to specify the (location of the) database.

Why don't you give it a try instead and let me know the results?

**Comment by blimeybloke** [comment]
hah, I did that before I knew about the --database command :)  I am sure that would work just as well too.
