### ISSUE TITLE
magneticow API v0

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#162]
Version 0.7.0 of **magnetico** will offer a simple REST-ful API for 3rd-party developers to make use of **magnetico**'s powers!

You can read the draft here: ~~https://app.swaggerhub.com/apis/boramalper/magneticow-api/v0~~

__UPDATED -> v0.1:__ https://app.swaggerhub.com/apis/boramalper/magneticow-api/v0.1

## What am I asking?
Your feedback! Is there anything that you think is redundant, or missing? Anything you think could be an improved, or that you are unsure about.

See #50 for previous discussion, and many thanks to @lozbrown for the initial idea and many others for their contribution! =)

**Comment by donaldsteele** [comment]
what about adding /search/{html encoded term}/{after|before}/{key}

after / before would be the direction to page and key would be the offset term . Instead of using limit move towards a key set pagination model (better performance) 

https://use-the-index-luke.com/no-offset

**Comment by donaldsteele** [comment]
Yes urlencode is the correct encoding

**Comment by boramalper** [comment]
In the current draft, there is a `discovered_on_before` parameter to ensure that new torrents won't disrupt the pagination, but obviously this doesn't protect against removed torrents; besides, very likely that there are edge-cases that I'm not even (yet) aware of.

I read about keyset pagination while trying to find a solution to this problem that I mentioned, but I have a question: as I understood, the idea is that the results are **always ordered** based on some column/property, and when we request the next page, we include the value of the last entry in the current page so that instead of `LIMIT l OFFSET n`, the database will add another condition to the `WHERE` clause.

For instance, if I'm ordering by `discovered_on` in descending order, and the timestamp of the last entry in the page is `1520421225`, do I say `/search/whatever+term/before/1520421225`? __But what if there are two entries with the same timestamp?__

Also: https://www.sqlite.org/rowvalue.html#scrolling_window_queries

**Comment by boramalper** [comment]
For SQLite3 it's in [pkg/persistence/sqlite3.go](https://github.com/boramalper/magnetico/blob/7e2a2bc5d9e527305c2c02b44bfe5efff201f896/pkg/persistence/sqlite3.go#L230):

```
		CREATE TABLE IF NOT EXISTS torrents (
			id             INTEGER PRIMARY KEY,
			info_hash      BLOB NOT NULL UNIQUE,
			name           TEXT NOT NULL,
			total_size     INTEGER NOT NULL CHECK(total_size > 0),
			discovered_on  INTEGER NOT NULL CHECK(discovered_on > 0)
		);
		CREATE TABLE IF NOT EXISTS files (
			id          INTEGER PRIMARY KEY,
			torrent_id  INTEGER REFERENCES torrents ON DELETE CASCADE ON UPDATE RESTRICT,
			size        INTEGER NOT NULL,
			path        TEXT NOT NULL
		);
		CREATE UNIQUE INDEX info_hash_index ON torrents	(info_hash);
			ALTER TABLE torrents ADD COLUMN updated_on INTEGER CHECK (updated_on > 0) DEFAULT NULL;
			ALTER TABLE torrents ADD COLUMN n_seeders  INTEGER CHECK ((updated_on IS NOT NULL AND n_seeders >= 0) OR (updated_on IS NULL AND n_seeders IS NULL)) DEFAULT NULL;
			ALTER TABLE torrents ADD COLUMN n_leechers INTEGER CHECK ((updated_on IS NOT NULL AND n_leechers >= 0) OR (updated_on IS NULL AND n_leechers IS NULL)) DEFAULT NULL;
			ALTER TABLE files ADD COLUMN is_readme INTEGER CHECK (is_readme IS NULL OR is_readme=1) DEFAULT NULL;
			ALTER TABLE files ADD COLUMN content   TEXT    CHECK ((content IS NULL AND is_readme IS NULL) OR (content IS NOT NULL AND is_readme=1)) DEFAULT NULL;
			CREATE UNIQUE INDEX readme_index ON files (torrent_id, is_readme);
```

and then there is also full-text search virtual table:

```
			CREATE VIRTUAL TABLE torrents_idx USING fts5(name, content='torrents', content_rowid='id', tokenize="porter unicode61 separators ' !""#$%&''()*+,-./:;<=>?@[\]^_` + "`" + `{|}~'");
            
			-- Populate the index
			INSERT INTO torrents_idx(rowid, name) SELECT id, name FROM torrents;
			-- Triggers to keep the FTS index up to date.
			CREATE TRIGGER torrents_ai AFTER INSERT ON torrents BEGIN
			  INSERT INTO torrents_idx(rowid, name) VALUES (new.id, new.name);
			END;
			CREATE TRIGGER torrents_ad AFTER DELETE ON torrents BEGIN
			  INSERT INTO torrents_idx(torrents_idx, rowid, name) VALUES('delete', old.id, old.name);
			END;
			CREATE TRIGGER torrents_au AFTER UPDATE ON torrents BEGIN
			  INSERT INTO torrents_idx(torrents_idx, rowid, name) VALUES('delete', old.id, old.name);
			  INSERT INTO torrents_idx(rowid, name) VALUES (new.id, new.name);
			END;

```

**Comment by donaldsteele** [comment]
shouldn't we be able to use the id and rank for the after / before limiter? 

select id, info_hash, name, total_size , rank(matchinfo(torrents)) as match_rank
from torrents 
where  name MATCH 'software'
and rank(matchinfo(torrents)) || id < {OFFSET}
ORDER BY rank(matchinfo(torrents)) DESC, id DESC

**Comment by boramalper** [comment]
@donaldsteele 

* What is `{OFFSET}`, is it the id of the last entry in the current page?
* How does this prevent new(-ly added) entries from disrupting the search?

Sorry if the questions are too trivial, I'm a bit too tired. =)

**Comment by donaldsteele** [comment]
no worries at all :) offset would be the last entry on the current page  and i actually have a typeo in my psudo code above , ID should be sorted asc not desc. since ID is auto generated this would place new entries on the next page since it would come after the last id as sorted by rank . I will try and whip up a test db to verify my logic is correct .  Now there is the very slight possibility that a new torrent that is a better match to the term is inserted after you have left the first page however this issue still exists when using limit .

**Comment by boramalper** [comment]
## Analysis 
I tried analysing the problem by clearly indicating the problematic cases that we need to deal with:

- There are two kinds of pages:

  1. Previous Pages
  2. Next Pages

   Think of Previous Pages and Next Pages as a list of list of result rows. For instance, the following is a result of a query with 9 results in total, and the user fetched two pages:

  ```
  Previous Pages:
      [[Row_1, Row_2, Row_3], [Row_4, Row_5, Row_6]]

  Next Pages:
      [[Row_7, Row_8, Row_9], []]
  ```

  The last list of rows in the previous pages (list) is what we call "the current page". Since every search requests returns a page (which might be empty), previous pages list must always have at least one list of results.

- There are three kinds of modifications/mutations that might happen during the search:

  1. Insertion (`INSERT INTO`)
  2. Update (`UPDATE`)
  3. Deletion (`DELETE`)

In the light of these two categories, we have the following table:

|                 | Insertion | Update<sup>†</sup> | Deletion |
|-----------------|:-----------:|:--------:|:----------:|
| __Previous  Pages__ |     *PI*     |   *PU*    |    *PD*      |
| __Next Pages__      |     *NI*      |    *NU*    |     *ND*     |

The first letter of the case indicates in which page the modified row lies in<sup>†</sup> (*i.e.* previous/next), and the second letter indicates the type of the modification/mutation. For example, *ND* indicates that a row in one of the next pages has been deleted.

†: We must beware that as a result of an Update operation might affect multiple pages! For instance, when sorted by the number of seeds (`n_seeders`), the same torrent might appear in multiple pages if its statistics were updated during the search. These cases are not represented by any of the symbols in our table.

## Proposal
I suggest adding a `has_readme` column to the torrents table, for the sake of convenience & performance, instead of running a sub-query again and again.

I suggest adding an `modified_on` column to the `torrents` table, which is a UNIX timestamp that indicates the last time the entry in modified.

- For newly added torrents, `modified_on` must be equal to `discovered_on`;
- Whenever a torrent's seeder/leecher statistics are updated, `modified_on` must be equal to `updated_on`;
- Whenever `has_readme` is updated, `modified_on` must be set accordingly.

In other words, whenever the attributes of a torrent changes, we must update `modified_on` accordingly. Lastly, a new `modified_on` value must always be greater than or equal to the value it replaces (*duh*). 

I also suggest adding an `epoch` parameter in each search query, which is a UNIX timestamp, to serve one rule:

- No torrent whose `modified_on` is greater than the `epoch` will be included in the results (*i.e.* `modified_on` (must be) <= `epoch` (for torrent to be included in the results)).

By adding the `epoch` parameter, we handle the following cases without further consideration:

- †
- All insertion cases (*PI* & *NI*)
- All update cases (*PU* & *NU*)

There are only two deletion cases left that we need to consider: *PD* and *ND*. Since we are using keyset pagination, deletions in the previous pages cannot disrupt an ongoing search, although the user will receive an error while accessing a deleted torrent (which would be still listed on the results page). And a deletion in the next pages have no harm at all, since they wouldn't even be aware of them.

Hence our query would look like this:

```sql
SELECT info_hash
     , name
     , total_size
     , discovered_on
     , updated_on
     , n_seeders
     , n_leechers
FROM torrents
INNER JOIN (
    SELECT docid AS id
         , rank(matchinfo(fts_torrents, 'pcnxal')) AS rank
    FROM torrents_idx
    WHERE name MATCH {QUERY}
) AS idx USING(id)
WHERE     modified_on    <= {EPOCH}
      AND total_size     >= {LAST_TOTAL_SIZE}
      AND id  < {LAST_ID}
ORDER BY total_size ASC, id DESC
LIMIT 10
;
```

Here we are searching torrents whose name matches a certain `{QUERY}`, ordered by their `total_size` in ascending order.

We are sorting once again by `id`, and in our query we compare each result's `id` with the `{LAST_ID}` to ensure that different results whose `total_size` are same but lies in different pages are not skipped.

----

Any questions?

**Comment by boramalper** [comment]
Since no one replied in the past 11 days, I assume everyone is happy with the proposal. Please do let me know if you have any objections or doubts, as I'll proceed to implementing it. =)

**Comment by izolight** [comment]
Will the epoch parameter be updated when pressing next in the results or will it be the epoch paramater of the original search?

**Comment by izolight** [comment]
I'm still a bit confused how lastOrderedValue and lastId should be used. Can you give an example?

**Comment by boramalper** [comment]
> I'm still a bit confused how lastOrderedValue and lastId should be used.

It is used for keyset pagination.

> Can you give an example?

Imagine you are querying torrents that contains "Ubuntu" in the title, sorted by the number of files in the ascending order, 3 results per page.

To get the first page, you make the following request:

    GET https://magnetico.org/api/torrents/?query=Ubuntu&epoch=1524061252&orderBy=N_FILES&ascending=1&limit=3

`epoch` is set to `1524061252` which is the UNIX Time at the beginning of the query.

You receive the following response (irrelevant fields are omitted):

```json
[
  {
    "id": 7,
    "name": "ubuntu-16.04.4-desktop-amd64.iso",
    "nFiles": 1,
    ...
  },
  {
    "id": 31,
    "name": "Ubuntu 16.04.4 + Manual",
    "nFiles": 2,
    ...
  },
  {
    "id": 12,
    "name": "Big Bucks Bunny Triology",
    "nFiles": 3,
    ...
  },
]
```

To get the next page, you need to make the following query

    GET https://magnetico.org/api/torrents/?lastOrderedValue=3&lastID=12&query=Ubuntu&epoch=1524061252&orderBy=N_FILES&ascending=1&limit=3

As you can see, `lastOrderedValue` is set to the `nFiles`, and `lastID` is set to `id`, both of the last entry in the returned list.

In the backend (*i.e.* __magneticow__), we would run a query like this:

```sql
SELECT info_hash
     , name
     , total_size
     , discovered_on
     , updated_on
     , n_files
FROM torrents
INNER JOIN (
    SELECT rowid AS id
         , bm25(torrents_idx) AS rank
    FROM torrents_idx
    WHERE torrents_idx MATCH 'Ubuntu'
) AS idx USING(id)
WHERE     modified_on <= {EPOCH}
      AND n_files     >= {LAST_ORDERED_VALUE if supplies else 0}
      AND id          <  {LAST_ID}
ORDER BY n_files ASC, id DESC
LIMIT 3
;
```

**Comment by izolight** [comment]
Yes, I didn't realise you were also ordering by the id on every query in addition to the main order. But that makes sense, otherwise of we just order by one non-unique value we would miss some results.

**Comment by boramalper** [comment]
I desperately want some feedback, does all of this make (at least) some sense to you?

**Comment by izolight** [comment]
If noone else replies that probably means they agree or don't care. If I were you I would just go ahead and start implementing it, you're the main author after all.

**Comment by donaldsteele** [comment]
boramalper this looks great.

**Comment by izolight** [comment]
What is the difference between updated_on and modified_on. You wrote that modified_on always changes when you change something about the torrent. Does updated_on only change when updating seeder/leecher count? Is there really a need to have both?

**Comment by slayer991** [comment]
Bumping.  I can see a real use for this with things like Jackett (which in-turn is used by things like Sonarr, Radarr, etc).  Without the ability for a 3rd party to call the API for searches...as cool this program is, the use-case for many will be limited.  Thank you.

**Comment by boramalper** [comment]
I am closing the issue as I consider the **magneticow** API mature enough at this point. With v0.8.1 (just released), all the rendering is now done client-side just so that we can dogfood our own API and see its shortcomings. =)

The documentation can be found at: https://app.swaggerhub.com/apis/boramalper/magneticow-api/v0.1

I expect no further changes to the API, except adding new fields. The only bug in **magneticow** regarding its implementation is that `/statistics` endpoint won't have keys for time periods if there are no data (whereas returning zeroes would be better); that shall be fixed soon too.

If you have any other requests, questions, _etc_, please open a new issue for _each_.

**Comment by boramalper** [comment]
> What is the difference between updated_on and modified_on.

@izolight Indeed it was a bit confusing, sorry about that. They were introduced for the upcoming seeder/leecher counts feature, but I removed them for now to keep things comprehensible.

I'll update it later on once I implement [BEP 33: DHT Scrapes](https://github.com/boramalper/magnetico/wiki/BEP-33:-DHT-Scrapes).
