### ISSUE TITLE
 No module named 'gevent.wsgi'

### ISSUE THREAD

**Issue by jackalblood** [boramalper/magnetico#169]
Hi there im running into an issue running magneticow its counterpart is fine however

`Traceback (most recent call last):
  File "/home/username/.local/bin/magneticow", line 7, in <module>
    from magneticow.__main__ import main
  File "/home/username/.local/lib/python3.5/site-packages/magneticow/__main__.py", line 21, in <module>
    import gevent.wsgi

ImportError: No module named 'gevent.wsgi'
`

I've tried 

sudo apt-get install python-all-dev

sudo apt-get install libevent-dev

 sudo apt-get install python-gevent python-gevent-websocket

python -m pip install gevent

this happens with and without arguments attached 

Thank you

**Comment by kylinblue** [comment]
go edit the main.py there are 2 places that used gevent.wsgi, rename both of them to gevent.pywsgi solves the issue

**Comment by jackalblood** [comment]
I have yet to find anything to help me with this issue

**Comment by deckar01** [comment]
This is still broken in the latest release.

**Comment by MKingNoCry** [comment]
try gevent.pywsgi

**Comment by deckar01** [comment]
Is there a reason `gevent.wsgi` is in the code base, but not available on my machine after installing all the documented dependencies?

**Comment by deckar01** [comment]
It looks like `gevent.wsgi` was an undocumented that was removed in gevent 1.3.0.

http://www.gevent.org/changelog.html#b2-2018-05-03

**Comment by boramalper** [comment]
Closing since we re-wrote **magnetico** in Go and this problem shall no longer exists. =)

**Comment by Snake87r** [comment]
go version doesn't work with rasperry now, because the installer of dep isn't compatible with it
