### ISSUE TITLE
PHP private web interface for magnetico database

### ISSUE THREAD

**Issue by skobkin** [boramalper/magnetico#170]
As in #51 I'd like to note that I've made simple web interface for magnetico database using PHP 7.2 and Symfony 4 (Flex).

It's OpenSource (MIT) and can be used by anyone:

https://bitbucket.org/skobkin/magnetico-web/

The main goal was to create alternative interface which could be hosted in the public network and will not cause any inadequate copyright claims because it's private (invite-only).

In the future I hope that magneticod will support database servers like PostgreSQL/MySQL and then I'll add support too and migrate my own instance to the PostgreSQL.

Also probably in the future I might add public mode but will not use it on my own instance.

**Comment by boramalper** [comment]
Updated the [wiki](https://github.com/boramalper/magnetico/wiki/Related-Projects#alternative-front-ends) and the README of **magneticow**. =)

**Comment by jangrewe** [comment]
@skobkin I wanted to try your project, but i'm only getting Postgres errors?
I've commented out `APP_DATABASE_URL` and only set `MAGNETICOD_DATABASE_URL` to the proper URL for my database (also tried with `APP_DATABASE_URL` set to the same), but it keeps trying to connect to PGSQL.

**Comment by skobkin** [comment]
@jangrewe Hi.

Sorry but it's intended behavior. It's **private** interface with (at least for now) authenticated-only access. It means that you must setup both databases (magnetico's SQLite and magnetico-web's PostgreSQL). First database will be used for torrents search and last for users storage and invite system.

The main goal of this project was to create alternative interface which can allow you to install it to the public server without showing to all outside world the content of your magnetico index.

Also I've just saw that I forgot to fully describe setup process. There are two missed setup steps:

* After configuring the database you must apply database migrations to create schema in PostgreSQL database: `php app/console doc:mig:mig --em=default`
* After creating schema you probably would want to create yourself a user in the system: `php app/console user:add <your_username> <your_email> [your_password] [--invites=10]` (see `--help` for more info)

Hope this helps. I'll update `README.md` in the root of the project repo soon to add these missing steps.

**Comment by skobkin** [comment]
@jangrewe You can try to experiment with `config/packages/security.yaml` file (`access_control` section) changing `ROLE_USER` to `IS_AUTHENTICATED_ANONYMOUSLY` but I will not guarantee that this will work for you because there may be more auth checks in the code not only in the configs and Symfony Security system may try to fetch your user from the database anyway.

Anyway this project was supposed to work with two databases (at least until magneticod starts to support PostgreSQL as storage backend).

**Comment by skobkin** [comment]
Just updated the [documentation](https://bitbucket.org/skobkin/magnetico-web/src/master/README.md). You can create the [issue](https://bitbucket.org/skobkin/magnetico-web/issues/new) if you found some problem.

**Comment by boramalper** [comment]
@jangrewe I think @skobkin would also appreciate if you use his bug tracker since the discussion is more relevant to his project than mine. =)
