### ISSUE TITLE
hello, can anyone tell me where the binary is?

### ISSUE THREAD

**Issue by goxofy** [boramalper/magnetico#177]

**Comment by FofeuLabs** [comment]
There is none. The provided Makefile does not work, there are no clear build instructions and @boramalper did not provide any sign of life since late September
When I find time, I will try to fix the Makefile and publish a binary
You can ping me again next week

**Comment by goxofy** [comment]
@FofeuLabs Thanks!

**Comment by boramalper** [comment]
@goxofy Check the [releases](https://github.com/boramalper/magnetico/releases) and [Docker Hub](https://cloud.docker.com/repository/docker/boramalper/magnetico). =)

**Comment by goxofy** [comment]
@boramalper hello, I have downloaded the binary from the releases, but where is the config file?

**Comment by boramalper** [comment]
@goxofy Sorry it was a mistake in the docs, no need for a configuration file. :)
