### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by Maxbanter45** [boramalper/magnetico#181]
Hey bora hows the go lang rewrite going? is this project still active

**Comment by milezzz** [comment]
Also been watching this closely =]

**Comment by boramalper** [comment]
Hey! [Just released v0.7.0.](https://github.com/boramalper/magnetico/releases/tag/v0.7.0) The project is alive but in desperate need of maintainers, so if you are willing to contribute, feel welcomed to ask questions and I'll be happy to get you on track. =)
