### ISSUE TITLE
Separate docker image repositories

### ISSUE THREAD

**Issue by skobkin** [boramalper/magnetico#185]
Now both magneticod and magneticow is in the same image repository `boramalper/magnetico`.

I think it would be more transparent to separate the images into the two repos. It allows you (and us) to have simplier version system. You wouldn't need to use long unclear tags like `d_v0.7.1`. You'll have simple `0.7.1` for both of the repos. Now there is also problem with unpredictable `latest` tag. We don't know to which image it will be pointing. If you separate the repos we can have `latest` tag in each of the repos to follow new versions more simple.

**Comment by boramalper** [comment]
Done! =) 

See [boramalper/magneticod](https://cloud.docker.com/repository/docker/boramalper/magneticod) and [boramalper/magneticow](https://cloud.docker.com/repository/docker/boramalper/magneticow).

**Comment by skobkin** [comment]
Nice, thanks!
