### ISSUE TITLE
search returns blank results, despite at least a few in index

### ISSUE THREAD

**Issue by jamesabruce** [boramalper/magnetico#19]
It's not discovered much, but nothing is listed in the web interface anyway. Output of magneticod (censored by me to avoid copyright issues):

```
2017-04-10 07:49:27,314      INFO  magneticod v0.1.0 started
2017-04-10 07:49:27,329     DEBUG  SybilNode 6033565F3F718D6EDA45D6AA9356A1AA624AE4FF initialized!
2017-04-10 07:50:34,240   WARNING  Belated TICK! (Δ = 3)
2017-04-10 08:10:30,532      INFO  Added: `**********[ettv]`
2017-04-10 08:10:43,009      INFO  Added: `************ия`
2017-04-10 08:10:50,722      INFO  Added: `******** Star ****************`
2017-04-10 08:20:19,872      INFO  Added: `*********************.avi`
```

magneticow debug:

::1 - - [2017-04-10 08:22:09] "GET /torrents/?search= HTTP/1.1" 200 1539 0.004133
::1 - - [2017-04-10 08:22:11] "GET /torrents/?search= HTTP/1.1" 200 1539 0.003614
::1 - - [2017-04-10 08:22:19] "GET /torrents?search=star HTTP/1.1" 301 480 0.001086
::1 - - [2017-04-10 08:22:19] "GET /torrents/?search=star HTTP/1.1" 200 1537 0.004578
::1 - - [2017-04-10 08:22:41] "GET /torrents/?search=star HTTP/1.1" 200 1537 0.004020
::1 - - [2017-04-10 08:22:44] "GET /torrents/ HTTP/1.1" 200 1539 0.003077
::1 - - [2017-04-10 08:22:46] "GET /torrents/ HTTP/1.1" 200 1539 0.002926
::1 - - [2017-04-10 08:22:51] "GET /torrents/?search= HTTP/1.1" 200 1539 0.003159
::1 - - [2017-04-10 08:24:21] "GET /torrents/?search= HTTP/1.1" 200 1539 0.002909
::1 - - [2017-04-10 08:24:27] "GET /torrents/?search=star HTTP/1.1" 200 1537 0.003034

Yet no search results are returned, either searching blank for all results, or "star" to try to confirm it's found one of the specific torrents listed. 

![screen shot 2017-04-10 at 08 29 33](https://cloud.githubusercontent.com/assets/2298025/24850404/e2709efe-1dc7-11e7-8b5c-62c726e0f375.png)

**Comment by boramalper** [comment]
**magneticod** adds torrents to the database in dozens so you should wait a little bit more. =)
