### ISSUE TITLE
Why not use a ORM(object relational mapping) for databases?

### ISSUE THREAD

**Issue by sterling-archermedes** [boramalper/magnetico#190]
On the matter of database abstraction I didn't see anyone mention ORMs but simply discuss other RDMS. So why not ORM's, such as GORM? The project would still work out of the box if the default config were left as sqlite and people could choose any other DB engine.

Note: I saw some people mention NoSQL. The project data can easily be abstracted as self contained documents that do not need atomicity so NoSQL could be used but I don't see much advantage in doing so.

**Comment by sterling-archermedes** [comment]
An ORM adds no significant performance penalty.

**Comment by ad-m** [comment]
Can you prove it by showing data?

**Comment by sterling-archermedes** [comment]
This question doesn't even make sense. What ORM A vs what ORM B and SQL written by whom? You don't expect me to choose an ORM and implement the changes all by myself only for the repo owner to say "no", right?

Also, no, additional transformations do not always add performance penalties. The ORM could use lazy evaluation or the queries could end up being much more optimized because a lot of people put thought on them.

**Comment by boramalper** [comment]
Hey @sterling-archermedes! In all honesty, the reason is as simple as my lack of experience with ORMs, and that me never feeling a need for it (which of course isn't completely valid, considering people want to use other databases).

I definitely would like to keep our [`pkg/persistence`](https://github.com/boramalper/magnetico/tree/master/pkg/persistence) abstraction, since I believe it can be immensely useful for some advanced/esoteric cases such as separating the database and the full text-search engine etc. but, that being said, if you can devise a way to use ORM (GORM or something else) without forcing users to migrate their database, I would genuinely be interested in it!

**Comment by skobkin** [comment]
@ad-m When thinking about using an ORM you need to think about use cases and bottlenecks. Some are not so good for ORM (large reports where too many data needs to be hydrated for example). But in many more or less simple cases ORM is very good. Magneticod main database operations are mostly simple `INSERT` and simple `SELECT` (for magneticow or other web interfaces). Typical throughput is 1-5 torrents per second or so. It's not the scale when ORM can become your bottleneck. The main and everlasting magneticod bottleneck is P2P connections and torrent data crawling.

In return we'll gain OO interface to operate our entities (torrents and files) and also we wouldn't need to write database-specific code for at least part of current database queries magneticod makes.

So for me more clear and database-agnostic code would be great to have. I even ready to migrate my database if it would be needed for some reason (most likely not).

**Comment by donaldsteele** [comment]
@skobkin an ORM does not automatically give you the ability to run against any database you wish. Generally speaking boramalper is correct , there is additional overhead that would potentially be a problem. That being said one of my previous pull requests added mysql as a target db and i had / have the postgresql patch as well. Once i get a bit of time i am more than happy to implement the patches using the current code base to add additional databases. If you are so inclined you should be able to find my old pull request and port mysql over if you need it sooner.

**Comment by skobkin** [comment]
@donaldsteele

> Generally speaking boramalper is correct , there is additional overhead that would potentially be a problem.

It's arguable if ORM will make any *noticeable* overhead in case of magnetico usage scanarios. Personally I don't think so.

> If you are so inclined you should be able to find my old pull request and port mysql over if you need it sooner.

I have my own PostgreSQL support prototype patch for new version and it works for magneticod part but have problem with non-unicode torrent names which could be found in DHT. Unfortunately right now I have no time to deal with this problem (also my expertise with Golang is very low).

**Comment by boramalper** [comment]
Closing the issue. Feel free to open more specific ones if anyone is willing to undertake the task of writing an abstraction that uses an ORM.
