### ISSUE TITLE
Eating up all the ram

### ISSUE THREAD

**Issue by signedbytes** [boramalper/magnetico#192]
After running for a couple of days, all the RAM is eaten up that I can't even login via ssh.
I configured magneticod and magneticow as instructed here and for the first few months it was okay except the problem with "commiting metadata to the database" which i've already asked here (https://github.com/boramalper/magnetico/issues/180) and then changed the required file and then run it again and it was running fine until couple of days ago which i've noticed that it's eating up all the memory till the point where even shell is not working anymore.

On host i'm only running magneticod and magneticow and nothing else.
I can't check the console/terminal for erros because i can't even login to ssh
what can I do ?

**Comment by ad-m** [comment]
@signedbytes , which version magneticow do you use? do you have any charts & metrics to show memory usage in time eg. collected via Zabbix?

**Comment by signedbytes** [comment]
> @signedbytes , which version magneticow do you use? do you have any charts & metrics to show memory usage in time eg. collected via Zabbix?

I am using version v0.6.0
and this is printscreen from digitalocean monitoring dashboard for charts:
![image](https://user-images.githubusercontent.com/10119075/53172591-012d3180-35e6-11e9-8054-e66804a7f428.png)

**Comment by signedbytes** [comment]
and these printscreen are from commands: top & htop

top:
![image](https://user-images.githubusercontent.com/10119075/53173377-d512b000-35e7-11e9-82fa-fdc688a677b9.png)

htop:
![image](https://user-images.githubusercontent.com/10119075/53173401-e360cc00-35e7-11e9-9b21-ba76bdff99c4.png)

**Comment by boramalper** [comment]
This shall be fixed with the recent versions. Closing the issue, but let me know if it persists with the recent versions too.
