### ISSUE TITLE
I can't find the configuration file

### ISSUE THREAD

**Issue by caecity43** [boramalper/magnetico#193]
via: https://github.com/boramalper/magnetico/tree/master/cmd/magneticod#configuration

I can't find the configuration file at `~/.config/magneticod/configuration.toml` after I run magneticod.

version: 0.7.1

**Comment by skobkin** [comment]
Seems like magneticod is not using it at all yet :man_shrugging:

It's not even importing `go-toml` and configuration name could not be found in the source code.

Looks like for now all we can use is CLI flags.

**Comment by boramalper** [comment]
Sorry! @skobkin is absolutely right, it's not implemented yet. I am not sure if it's required either, I don't know if anyone has a strong preference of config files over cmd-line flags.

Closing the issue as I have now updated the README. =) Feel free to create a new issue if you think having a configuration file is worthwhile.
