### ISSUE TITLE
Let the user specify IP/interface to bind to

### ISSUE THREAD

**Issue by guppy42** [boramalper/magnetico#20]
Currently it binds to 0.0.0.0
https://github.com/boramalper/magnetico/blob/257912a12f862d9f4ca3c5970df57f3a62d29c66/magneticod/magneticod/dht.py#L45

This should be configurable ( defaulting to 0.0.0.0 ) so users with multiple interfaces can specify which to use.

This is useful if you have multiple interfaces with valid routes, which may happen if you have for instance a dedicated VPN interface and a normal interface. In this case it would be nice to be able to choose either the secure or the fast interface.

Since the program does not throttle it self this would also allow throttling it via traffic shaping

**Comment by boramalper** [comment]
Done in v0.2.0!
