### ISSUE TITLE
Add more bootstrap address

### ISSUE THREAD

**Issue by lopoki** [boramalper/magnetico#200]
Please add more bootstrap address 

                "router.utorrent.com:6881",
		"router.bittorrent.com:6881",
		"dht.transmissionbt.com:6881",
		"dht.aelitis.com:6881",     // Vuze
		"router.silotis.us:6881",   // IPv6
		"dht.libtorrent.org:25401", // @arvidn's

**Comment by Glandos** [comment]
I'm not sure `magneticod` supports IPv6. See #91

**Comment by boramalper** [comment]
@Glandos That is indeed correct.

I am also afraid that Vuze DHT is not using Mainline DHT (they are different networks using different protocols), unless things have changed recently. See more details here https://wiki.vuze.com/w/Distributed_hash_table

I can add utorrent's tracker myself, or you can try submitting a PR. [It should be fairly trivial](https://github.com/boramalper/magnetico/blob/v0.8.1/cmd/magneticod/dht/mainline/indexingService.go#L104), and I would like to encourage more people to become a contributor. =)
