### ISSUE TITLE
Support for splitting db file as it reach certain size

### ISSUE THREAD

**Issue by lopoki** [boramalper/magnetico#205]
I'm not comfortable with having one single huge database file . 
Please support splitting database files as  it reach certain size, for example as db file reach 5GB, magneticod will start writing into new file instead of appending to the original db file.

Better yet please add support for other db suchh as mongod etc. Anything other than sqlite.
There's another similar project as magneticod written in erlang 2 years ago in github repo. See my forked version. You might get ideas to improve magneticod from there.

**Comment by Glandos** [comment]
Did you experienced real issues with SQLite ? I'm running `magneticod` on a Intel Atom D2550 with 4GB of RAM, my database is 8.2 GB stored on an SSD, and I'm far from having troubled with it.

**Comment by jbruchon** [comment]
SQLite is designed for exactly the sort of thing that's being done here. Splitting the DB will make things needlessly complex. It also takes a while to grow it to such a huge size. I have around 75K torrents and my DB is 162 MiB. MongoDB would be a terrible choice for a project like this.

**Comment by lopoki** [comment]
I collect around 250k torrents in less than 2 days and the size of db grows fast. I don't have problem with size yet but at this rate will collect well around 7million torrents in a month and that is when I expect I probably will have problem and needs to export the db to some other db for real use of Web app.

**Comment by jbruchon** [comment]
SQLite performance is nearly constant if a primary key and indexing is used, even with a table containing millions of entries: https://stackoverflow.com/questions/33456278/sqlite-performance-on-large-tables

Having an index can cause insertion slowdown for large insertions though: https://stackoverflow.com/questions/15778716/sqlite-insert-speed-slows-as-number-of-records-increases-due-to-an-index

Dropping indexes, inserting, and recreating indexes solves the problem for inserting large amounts of data and is the accepted way to deal with it: https://medium.com/@JasonWyatt/squeezing-performance-from-sqlite-indexes-indexes-c4e175f3c346

I would imagine that it's not terribly difficult to convert the program to something sensible for large data sets like MySQL/MariaDB. I'd guess @boramalper would appreciate a pull request making that an option.

**Comment by lopoki** [comment]
IMHO sqlite is not the correct choice food this type of project, but that's up to @boramalper .
People who claim that sqlite can handle large data always add caveat that it has "the right setting" . And that part is the most important thing from that statement. I have a web app that work with large sqlite data around 35GB and you must optimize often and  fine tune often to get a usable good enough performance. At that point ssd and ram doesn't help much.

If I collect torrent at this rate , in a year I'm well off 84 million torrent assuming most people turn on duty setting in the torrent client, sooner rather than later sqlite will be the bottleneck or at least reduce magneticod performance overall.

**Comment by jangrewe** [comment]
I just want to put in my vote for "anything other than SQLite". Maybe we don't need a full ORM, but at least some abstraction that allows me to use MySQL, or even Postgres if i have to, would probably be a better idea than starting to work around the potential issues with SQLite.

**Comment by boramalper** [comment]
I think splitting the database would be far too complicated so I kindly refuse that idea.

I agree that it'd indeed be great to have support for other databases but I sadly have no time. Feel free to create *specific* issues for the databases (or architectures) you'd like to see supported, and see if there is anyone interested in implementing them.
