### ISSUE TITLE
Go version

### ISSUE THREAD

**Issue by ad-m** [boramalper/magnetico#207]
Which Go version should be used to build application?

CI mention one version:
https://github.com/boramalper/magnetico/blob/master/appveyor.yml#L16

Dockerfile mention another:
https://github.com/boramalper/magnetico/blob/master/Dockerfile.magneticod#L3

**Comment by jangrewe** [comment]
If it builds with 1.12, build it with 1.12. If you only have 1.11, use 1.11.
In short: If it builds, it builds. ;-)

**Comment by boramalper** [comment]
@jangrewe Well, correct. =)

@ad-m I think it's safe to say that you can always use the latest 1.X version of Go. I'll try to be more careful about consistency in the future.
