### ISSUE TITLE
magneticow build test failed

### ISSUE THREAD

**Issue by elig0n** [boramalper/magnetico#208]
go test ./...
    # github.com/boramalper/magnetico/cmd/magneticow [github.com/boramalper/magnetico/cmd/magneticow.test]
    cmd/magneticow/handlers.go:102:15: undefined: Asset
    cmd/magneticow/main.go:196:15: undefined: Asset
    ok      github.com/boramalper/magnetico/cmd/magneticod  (cached)
    ok      github.com/boramalper/magnetico/cmd/magneticod/bittorrent/metadata      (cached)
    ?       github.com/boramalper/magnetico/cmd/magneticod/dht      [no test files]
    ok      github.com/boramalper/magnetico/cmd/magneticod/dht/mainline     0.004s
    FAIL    github.com/boramalper/magnetico/cmd/magneticow [build failed]
    ok      github.com/boramalper/magnetico/pkg/persistence (cached)
    ?       github.com/boramalper/magnetico/pkg/util        [no test files]
    make: *** [Makefile:29: test] Error 2

**Comment by rnhmjoj** [comment]
I figured the error is due to the fact the prerequisites of the `all` make target are out of order.
`test` should be built last, after magneticow.

**Comment by boramalper** [comment]
Thanks for reporting! Travis build passed with the latest commit & version so I presume the issue no longer persists.

Closing this issue, but feel free to open new ones if the build breaks again.
