### ISSUE TITLE
Docker launch instructions?

### ISSUE THREAD

**Issue by Azat868** [boramalper/magnetico#209]
```bash
docker pull boramalper/magneticod
docker create -t -i docker.io/boramalper/magneticod
docker start romantic_kalam
```
![изображение](https://user-images.githubusercontent.com/29046741/60330599-785f4180-999b-11e9-997b-0e28a61e24cf.png)
Tell the newcomer how to run the container?

**Comment by jangrewe** [comment]
Let's say you want to persist the database in `/opt/magnetico` and want to access the web interface on port `12345`:
```
docker run -d --name magneticod -v /opt/magnetico:/home/magnetico/.local/share/magneticod boramalper/magneticod:latest -v
docker run -d --name magneticow -p 12345:8080 -v /opt/magnetico:/home/magnetico/.local/share/magneticod  boramalper/magneticow:latest --no-auth -v
```

You should probably also have a look at the `docker run` documentation...

**Comment by chovy** [comment]
I get an error about a missing credentials file.

**Comment by boramalper** [comment]
@Azat868 Also see

- https://github.com/boramalper/magnetico/blob/master/cmd/magneticod/README.md#using-the-docker-image
- https://github.com/boramalper/magnetico/blob/master/cmd/magneticow/README.md#using-the-docker-image

@chovy Answered at #212.
