### ISSUE TITLE
Asian text shown and saved as �

### ISSUE THREAD

**Issue by DyonR** [boramalper/magnetico#221]
magneticod/w has issues presenting and saving Asian characters. Any characters are just shown and saved as � instead of the actual character. Weirdly, I also see records with proper naming.
Just a random torrent I saw in magneticow:
https://i.imgur.com/kjtk5nQ.png

Adding this torrent to my client to see how it should be:
https://i.imgur.com/JXX0oZE.png

Checking it in the databse:
https://i.imgur.com/ehldvzg.png

**Comment by skobkin** [comment]
Which codepage was used in original data from DHT?

If it was not UTF-8 then it's probably expected behavior.

**Comment by boramalper** [comment]
Thank you for taking time to report this!

@skobkin is right, the only supported encoding is UTF8, which is thankfully widespread such that the cases such as you have mentioned are exceptional.

Of course it is possible to try detect the encoding of text, but it's (a) slow and (b) comes with an increased complexity so I am against it.
