### ISSUE TITLE
Checking if a peer is a seeder

### ISSUE THREAD

**Issue by lruggieri** [boramalper/magnetico#230]
Hello,

I was wondering how to check if a peer can be considered a seeder.

The fact that it responds to our request for an infohash with metadata info makes it a peer but not necessarily a seeder, right?
To say it's a seeder it should have all pieces of the torrent with the infohash we asked. So should we ask specifically for each piece (Info.**Pieces**)
```
type Info struct {
	PieceLength int64  `bencode:"piece length"`
	Pieces      []byte `bencode:"pieces"`
	Name        string `bencode:"name"`
	Length      int64  `bencode:"length,omitempty"`
	Private     *bool  `bencode:"private,omitempty"`
	// TODO: Document this field.
	Source string     `bencode:"source,omitempty"`
	Files  []FileInfo `bencode:"files,omitempty"`
}
```

that is present in the torrent metadata to the peer? If that's the case, how do we do it? Which is the correct request to make?

**Comment by boramalper** [comment]
> The fact that it responds to our request for an infohash with metadata info makes it a peer but not necessarily a seeder, right?

I think so, correct! Though, for our purposes, I don't think we need seeders only either.

> To say it's a seeder it should have all pieces of the torrent with the infohash we asked. So should we ask specifically for each piece

Assuming I understand it right, requesting each piece would be downloading the torrent wouldn't it? =)

I don't really know (or at least can't remember right now) how a client can know whether a given peer is a seeder or not. You might want to ask on [anacrolix/torrent](https://github.com/anacrolix/torrent) or [arvidn/libtorrent](https://github.com/arvidn/libtorrent).

**Comment by anacrolix** [comment]
@lruggieri I believe the typical classification for a seeder is a peer that already has the entire torrent, but remains on the network (presumably to seed).

**Comment by lruggieri** [comment]
> @lruggieri I believe the typical classification for a seeder is a peer that already has the entire torrent, but remains on the network (presumably to seed).

that's correct! I was wondering though if there was an easy way to understand if the peer we are connecting to has the whole torrent and if therefore a seeder

**Comment by lruggieri** [comment]
btw I believe the answer to this question is to implement BEP33, as expressed in several other issues
