### ISSUE TITLE
Credential

### ISSUE THREAD

**Issue by cyberlauncher** [boramalper/magnetico#246]
Excuse my ignorance but what is the username and password for magneticow?

**Comment by kescherCode** [comment]
https://github.com/boramalper/magnetico/blob/master/cmd/magneticow/README.md#setting-password-protection

**Comment by cyberlauncher** [comment]
Thank you Sir.
I just needed to be more thorough in reading the Readme!

**Comment by kescherCode** [comment]
Since this issue is resolved, you should close it.

**Comment by cyberlauncher** [comment]
The obvious had been president. 
Closing
