### ISSUE TITLE
No Web Interface when starting magneticow

### ISSUE THREAD

**Issue by DeRock89** [boramalper/magnetico#25]
Im attempting to run your two programs on Lubuntu running through VirtualBox because my machine is Windows 10.

When i initialize the command in ternimal to run Magneticow, I dont get any sort of web interface. The Terminal is just blank like it would be if a normal application GUI was initialized through terminal. I have to press Control C to return to a normal Terminal. 

It appears to be working normally when i run the command to asses magniticow's status 
` magneticow.service - magneticow: lightweight web interface for magnetico
   Loaded: loaded (/home/****************/.config/systemd/user/magneticow.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-13 00:11:38 EDT; 2min 40s ago
 Main PID: 1696 (magneticow)`

"**********" is my correct home directory, I just didn't want to put the name on here...

When i run Magneticod, I get:
`WARNING Belated TICK! (Δ = 5)`

Im more concerned with not having the web interface. I cant assess if even with the "Belated TICK" error if its even finding any files for the Web search interface.

**Comment by scriptzteam** [comment]
you need more GHz in your CPU its slow, had the same before, but could also be other problem as you run it in Virt.Box try real server, or allocate more CPU to Virt. Box ;)
