### ISSUE TITLE
Archlinux package available

### ISSUE THREAD

**Issue by rakoo** [boramalper/magnetico#268]
Hey there ! First, thanks a lot for magnetico it's working really nice out of the box, truly amazing!

I've taken the liberty to create the Archlinux package on AUR: https://aur.archlinux.org/packages/magnetico-bin. There's no real action needed right, now, I just wanted to reach out; feel free to ask/request anything if needed !

**Comment by rakoo** [comment]
And closing because nothing needs to be done, but discussion can continue

**Comment by kescherCode** [comment]
You might want to "magnetico" and "magnetico-git" as well.

**Comment by rakoo** [comment]
I mostly intend to use magnetico for personal use, so I probably won't be able to maintain all 3 packages like that. I'll let anyone else who's interested step up to the task :)
