### ISSUE TITLE
Peers / Seeds?

### ISSUE THREAD

**Issue by teamcoltra** [boramalper/magnetico#28]
What would be the difficultly level of adding peers and seeds, this goes a long way to checking dead and popular torrents.

**Comment by boramalper** [comment]
This requires implementing [BEP 33](http://www.bittorrent.org/beps/bep_0033.html), which in our [roadmap](https://github.com/boramalper/magnetico/wiki/Roadmap).

**Comment by boramalper** [comment]
@josch That's right, I must have missed that. Thanks!

**Comment by anacrolix** [comment]
@boramalper is there a new location for the [roadmap](https://github.com/boramalper/magnetico/wiki/Roadmap)?
