### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ngosang** [boramalper/magnetico#34]
Python 3.6.1 in Windows 10 x64
https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/bittorrent.py#L181
```
        self.__outgoing_buffer += b"%s\x14\x00%s" % (
            (2 + len(msg_dict_dump)).to_bytes(4, "big"),
            msg_dict_dump
        )
```
That code gives me an exception. I fixed it with this code but it's ugly:
```
        self.__outgoing_buffer += b"%s\x14\x00" % (2 + len(msg_dict_dump)).to_bytes(4, "big")
        self.__outgoing_buffer += msg_dict_dump
```

**Comment by boramalper** [comment]
This is not a bug in **magneticod** but in Python 3.6.0 to 3.6.1 (inclusive). It's clearly indicated in the installation instructions as well, so not considered a bug.
