### ISSUE TITLE
Randomness of random bytes

### ISSUE THREAD

**Issue by ad-m** [boramalper/magnetico#45]
My awareness take how much randomness need to be in ``DisposablePeer.__random_bytes`` (https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/bittorrent.py#L289 ). It take 6% of total script time. 

It really need to be random? Maybe it might be sequential?

**Comment by ngosang** [comment]
Not need to be random, it works fine but it's not fully bittorrent compliance.

**Comment by ngosang** [comment]
PR  #43 increases random bytes generation speed by 31%
