### ISSUE TITLE
Can we speed things up? In the mean of discovery new magnets

### ISSUE THREAD

**Issue by scriptzteam** [boramalper/magnetico#48]
`uptime
 09:40:28 up 10 days, 16:31,  1 user,  load average: 1.03, 1.04, 0.97`

So system is up for 10 days.

nload traffic cmd says:
```
in: 912.90 GByte
out: 476.86 GByte
```

So if we do some math i only do about 90Gbyte per day so its not a lot.

Can it be better, or need more cpu & ram?

**Comment by ngosang** [comment]
awesome speed up here => #43
