### ISSUE TITLE
[BETA-ShowOff] PHP Frontend with apache2

### ISSUE THREAD

**Issue by scriptzteam** [boramalper/magnetico#51]
Php + apache2 + python as backend (discovery index only - magneticod) :)

I dont really like confortable to have python based web frontend (magneticow), i am good with it as backend (magneticod).

So i did some quick coding and made a php version, basically just connecting to the db and choosing what to do. 

For me php seems faster than python as web platform.

**Demo**

Base-page:
https://dht.bittor.ch/

Base-page search:
https://dht.bittor.ch/?search=ubuntu

Base-RSS:
https://dht.bittor.ch/rss

Base-RSS search:
https://dht.bittor.ch/rss?search=ubuntu

Base-RSS search with limits number of output:
https://dht.bittor.ch/rss?search=ubuntu&limit=5

Basic magnet view:
https://dht.bittor.ch/?id=145916

Basic magnet files view:
https://dht.bittor.ch/?files=145916

This will change in future :)

**Comment by boramalper** [comment]
Well, if it's not *at least* open source, I have to ignore this. Else, I would be happy to add it to the wiki & documentation for those who might prefer a different interface. =)

Also, if not already, please "watch" the repository for changes so that when there is a change to the database, you can update your web interface accordingly.

**Comment by boramalper** [comment]
Also, it's really fast, I loved it! What machine is it running on?

**Comment by scriptzteam** [comment]
Its magic cpu :) not really its home server, one of many that i own, but this one got i7 (pc part server)

anyway php+apache2 frontend use not so much in compare to python frontend :D

I will make it open code soon, just optimizing the code which will speed it up again ...

**Comment by boramalper** [comment]
Cool, I'm closing the issue now, feel free to bump once it's ready (and *free*). =)

**Comment by scriptzteam** [comment]
Added tags to view page:
https://dht.bittor.ch/?id=143744

Added new recently discovered files page:
https://dht.bittor.ch/files

Added new simple stats page (new magnets per days):
https://dht.bittor.ch/stats

More updates to follow soon.

**Comment by boramalper** [comment]
Alpha reign had a very interesting tagging system, and they also released their source code after shutting down the site; you might want to check it out.

**Comment by scriptzteam** [comment]
Added pagi panation :D

Added on base main page stats how much was discovered last and this hour 
Example:
"Added last hour: +899
Added this hour: +1886"

**Comment by scriptzteam** [comment]
Json-API with search and limit output (limit can be max. 100):
https://dht.bittor.ch/api?search=ubuntu&limit=3

Json-API latest 1000:
https://dht.bittor.ch/api
