### ISSUE TITLE
Whats about privacy?

### ISSUE THREAD

**Issue by Translator5** [boramalper/magnetico#52]
Do the two clients communicate or just gather information from the net?
Do my client also upload sth.? Is my IP safe from being sending to stb.?
Is anonymity also guaranteed, as autonomous?
How safe is it so use is at this stage of dev.?

**Comment by ad-m** [comment]
@Translator5 , this is definitely network application, so two client communicate. Your client doesn't send personal info. ``magnetico`` doesn't guarantee anonymity - there is direct connection, so IP leak occurs. Anybody which ``magnetico`` connect can register ``magnetico`` client IP.
