### ISSUE TITLE
Switch to better-bencode instead of bencoder.pyx

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#72]
@itdaniher did the following benchmark:

```
>>> import timeit
>>> import bencoder
>>> import better_bencode
>>> test = {b"this":b"is", b"a":{b"test":b"dict"}}
>>> timeit.timeit('bencoder.bencode(test)', number=1000, globals=globals())
0.7214100720011629
>>> timeit.timeit('better_bencode.dumps(test)', number=1000, globals=globals())
0.016897161956876516
>>> better_bencode.dumps(test)
b'd1:ad4:test4:dicte4:this2:ise'
>>> bencoder.bencode(test)
b'd1:ad4:test4:dicte4:this2:ise'
>>> timeit.timeit('bencoder.bencode(test)', number=1000, globals=globals())
0.7153539570281282
>>> testb = b'd1:ad4:test4:dicte4:this2:ise'
>>> timeit.timeit('better_bencode.loads(testb)', number=1000, globals=globals())
0.009499340958427638
>>> timeit.timeit('bencoder.bdecode(testb)', number=1000, globals=globals())
0.10559769294923171
```

Apparently, [better_bencode](https://pypi.python.org/pypi/better-bencode/0.2.0) is nearly two orders of magnitude faster.

Benchmark once again, and use better-bencode instead.

**Comment by Glandos** [comment]
```
pip install bencoder.pyx
pip install better_bencode
```
And after that:
```
>>> import bencoder, timeit, better_bencode
>>> timeit.timeit('better_bencode.dumps(test)', number=1000000, globals=globals())
1.2166311100008897
>>> timeit.timeit('bencoder.bencode(test)', number=1000000, globals=globals())
31.603372027981095
>>> testb = b'd1:ad4:test4:dicte4:this2:ise'
>>> timeit.timeit('better_bencode.loads(testb)', number=1000000, globals=globals())
0.5871165109565482
>>> timeit.timeit('bencoder.bdecode(testb)', number=1000000, globals=globals())
4.7995752790011466
```

It was done with Python 3.6.1 (default, Mar 23 2017, 13:04:44) [GCC] on linux

**Comment by itdaniher** [comment]
Okay, only 25-30x speedup on your machine. :slightly_smiling_face:

**Comment by boramalper** [comment]
Hello! Unfortunately better_bencode does *not* provide a functionality where the end (last byte) of a bencode dump is not returned. This is currently provided by the 'loads2()` function in bencode.py file.

Any solutions?

**Comment by boramalper** [comment]
Okay, now I'm modifying the source so that we can fork it and use it as suitable to our needs. =)

**Comment by Glandos** [comment]
As witnessed in https://gitter.im/magnetico-dev/magnetico-dev?at=5935b5247503e2b706134704 the last commit renders magneticod useless, also for me.
Reverting the commit makes it work again (and it is now really fast with asyncio/uvloop)

**Comment by boramalper** [comment]
@Glandos I'll investigate the problem today. It should work and increase the performance even further.

**Comment by boramalper** [comment]
@Glandos fixed with a0ee71a. =)

**Comment by Glandos** [comment]
I confirm the fix. Many thanks!

**Comment by boramalper** [comment]
You're welcome. =)
