### ISSUE TITLE
Search & retrieval is too slow

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#8]
I realized that search is running way too slow to be tolerable: on my 5$ Linode instance, search takes around 22-30 seconds with (~500,000 torrents) even when **magneticod** is stopped (it may also vary depending on the search query).

Nevertheless, this must be resolved.

**Remarks:**
* We should create an index for the `info_hash` column in `torrents` table, to make torrent retrieval make torrent retrieval (which is based on the torrent's info hash) as fast as it could possibly be (actually, I should have created it at the very beginning...).
* I honestly don't know how to improve full-text search (in titles) performance. Currently, **magneticow** is using [Okapi BM25](https://en.wikipedia.org/wiki/Okapi_BM25) to rank the results, and the function is defined in Python itself which probably causes lots of overhead in SELECT queries. Removing the functionality might make it faster, but then we cannot rank the torrents by relevance and it will also make searching files of torrents almost impossible, as the results will be cluttered with least relevant torrents without a ranking mechanism.

  I am wide open to any suggestions and contributions in this regard. =)

**Comment by itdaniher** [comment]
Whoosh!

**Comment by itdaniher** [comment]
searches 200k torrents on a 500mhz machine in 15ms or less...

**Comment by boramalper** [comment]
> Whoosh!

I thought it's an exclamation, saying how fast the *current* implementation works for you (and I was quite happy for a moment).

I'm looking at whoosh right now, thanks!

**Comment by single-wolf** [comment]
Thanks for your great work,it works well ,but the search funtion does not support  Chinese and other Asian language.After set fts4 tokenize=unicode61,i can search the relevant torrents with 关键词+* .It seems noit a bad idea.Hope my suggestion can be useful. :-)

**Comment by itdaniher** [comment]
If we have a sqlite index on the names and infohashes row, it shouldn't be all that slow, but Whoosh will almost certainly be faster. 

I'll see if Whoosh and sqlite can play well together....

**Comment by itdaniher** [comment]
```
        self.conn = sql.connect('database.db')                                                                                                                                                                
        init_readings = 'CREATE TABLE IF NOT EXISTS readings (Timestamp REAL, Sensor INT, Units INT, Value REAL)'                                                                                                  
        self.conn.execute(init_readings)                                                                                                                                                                           
        create_index = 'CREATE INDEX IF NOT EXISTS time ON readings (Timestamp ASC)'                                                                                                                               
        self.conn.execute(create_index)                                                                                                                                                                            
        self.conn.commit()                                                                                                                     
```

here's an example of using sqlite indexes. did a quick `grep -ri` for creating indexes, didn't see it.

**Comment by boramalper** [comment]
@itdaniher But we are using a FTS virtual table for full-text search, I don't think that we need to create an index on the `torrents` table for the name column (except info hash which is used for viewing a specific torrent). I couldn't find it in [SQLite docs](https://sqlite.org/fts3.html) either, can you point on why it is required?

**Comment by itdaniher** [comment]
```
An index helps speed up SELECT queries and WHERE clauses, but it slows down data input, with UPDATE and INSERT statements. Indexes can be created or dropped with no effect on the data.
```

https://www.tutorialspoint.com/sqlite/sqlite_indexes.htm

**Comment by boramalper** [comment]
@itdaniher But still, indexes are *not* required if you are using FTS, which is a special case as it's a virtual table which maintains its own full-text search index.

**Comment by itdaniher** [comment]
Certainly not required, and if you're not doing SELECTs in response to user input, then improving the speed of the query against the sqlite db won't make things more responsive.

**Comment by nneonneo** [comment]
SQLite FTS5 includes a BM25 function - https://sqlite.org/fts5.html#the_bm25_function - perhaps this can be used in place of a Python implementation?

**Comment by boramalper** [comment]
@nneonneo FTS5 is not as widely supported as FTS3/4 so unfortunately we cannot use it (although it would be very nice).

**Comment by ad-m** [comment]
In #41 was said: 
>> I would be also very much grateful if you can analyse the SQL queries in magneticow, if you can. Queries are extremely slow and I honestly don't know why.

> You aren't doing anything wrong. SQLite is not designed to store many documents, performance is degraded after few thousand rows. If you want to use a relational DB use MySQL or PostgreSQL instead. SQL syntax is almost the same and your queries will be x10000 times faster. Since it's a search engine, using Elasticsearch (no relational search engine) will be awesome but you have to change to much code...

In my opinion there is lack of data transfer layer. We should think about separated layer to persistence and retrieve data object. Next to we can easily swap backend, test them and select the best.

I would like drop link about NoSQL & SQL database difference https://github.com/donnemartin/system-design-primer/#sql-or-nosql  I don't know next goals, but it might be suitable to use document store database. Now we have well suitable database (see https://github.com/boramalper/magnetico/blob/1c15afb45a6bdf3f617b5700205c5edf8798da32/magneticod/magneticod/persistence.py#L48 ).
