### ISSUE TITLE
Seems working, but nothing discovered

### ISSUE THREAD

**Issue by Bentzia** [boramalper/magnetico#85]
Hi there!

magneticod v0.4.0 installed OSX 10.12.4 using python 3.6, running since ~110 minutes
magneticow reports "~0 torrents available"

Log from magneticow doesn't report any problem. It's very quite, actually. There are only two lines:
2017-06-03 09:44:50,328  INFO      magneticod v0.4.0 started
2017-06-03 09:44:50,358  INFO      SybilNode [hexadecimal hash] on ('0.0.0.0', 0) initialized!
[Now it's 11:34]

Activity Monitor shows high outgoing traffic by python

Am I doing anything wrong?

Thanks

**Comment by ad-m** [comment]
Will you notice incoming traffic? Is port forwarding not configured?

**Comment by Bentzia** [comment]
There are some incoming traffic, but it's six times smaller than the outgoing traffic. What port I need to get forwarded?

Thanks

**Comment by ad-m** [comment]
@Bentzia , magneticod randomize ports by default. If you like use static port use ``magneticod --node-addr 0.0.0.0:8090``. 

@boramalper , what do you think about docs that?

**Comment by boramalper** [comment]
@ad-m Yeah I need to update the docs. I think I'll do it with the new release.

**Comment by Bentzia** [comment]
The port trick worked. I changed the machine (now a raspberry 3) in which I'm running magneticod and using Python 3.5.3 (installed from .tgz, because it's not in the raspbian jessie distribution)

All is fine but the #97 issue

Thanks!

**Comment by boramalper** [comment]
Closing the issue due to age, also because we now have a better method (indexing, instead of brute forcing...) to discover new torrents. =)

Feel free to open a new issue if the problem persists.
