### ISSUE TITLE
Establishing Contributions Guidelines

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#86]
Project is getting traction and quite a bit of interest for a while and I think it would be beneficial for all if we established certain guidelines for contributions.

What is to be done:

- [x] Write coding guidelines.
- [x] Setup Travis CI accordingly to check any PR requests and track the current status of the branch.

To elaborate more on coding guidelines:

- Following [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) in general.
- Enforcing static type checking using mypy.

   This would allow us to catch many `RuntimeErrors` on "compile" time. Also PyCharm (and presumably many other Python IDEs) offer a much better support for autocomplete and refactoring. Clear annotations also help programmer by providing what data type to expect. In general, unless you have a clear reason otherwise, **annotate!**

   - Annotate all function and method signatures.

----

We can also write unit and integration tests, but I am not going to volunteer personally. I really have no idea nor experience on developing tests (and I find them quite a bit waste of time). Although I would gladly accept any tests, but beware that project is still maturing and refactors and huge changes do happen.

**Comment by ad-m** [comment]
What about code of conduct? 😉 

Maybe you want to ponder issues with https://bestpractices.coreinfrastructure.org/? You will know what needs to be improved to make the project a friendly, open community workplace.

**Comment by boramalper** [comment]
@ad-m Sure! I'm closing the issue now but I added your suggestion to the "Projects" board. =)
