### ISSUE TITLE
magneticod only saves new results on graceful shutdown

### ISSUE THREAD

**Issue by Maverik44** [boramalper/magnetico#87]
magneticod finds a new results.
Check web interface..  0 count
Wait 1 hour
magneticod finds more results.
Check web interface..  0 count
Wait 2 hours 
magneticod finds more results.
Check web interface..  0 count
Ctrl - C to end end graceful
6 torrents added.
Check web interface.. 6 count

Any idea why magneticod has to exit graceful in order to save the results so the web interface sees whats being discovered.

**Comment by boramalper** [comment]
Hello @Maverik44! **magneticod** saves new torrents to the database in dozens by default so you should wait until at least 10 torrents are discovered.

**Comment by ad-m** [comment]
@Maverik44 , redirect ports. You should find dozens of torrents per minute.

**Comment by Maverik44** [comment]
okay perfect
