### ISSUE TITLE
[uvloop] Try to remove call to .encode('idna')

### ISSUE THREAD

**Issue by Glandos** [boramalper/magnetico#92]
I'm opening this issue because I don't have time to investigate more.

But in https://github.com/boramalper/magnetico/blob/master/magneticod/magneticod/dht.py#L80 the delegated `sendto` method calls `.encode('idna')` if the hostname is a string. This is really a waste of resource on my machine (~5% of total execution time on a 5 minutes benchmark).
Replacing the call with `self._transport.sendto(data, (addr[0].encode(), addr[1]))` on line 82 makes it really faster.
This behavior was observed while using uvloop. This is NOT visible when usinc asyncio.

The proposed fix CANNOT be the solution. I want to be sure that the address is always an IP address. Since it is the address provided by `datagram_received`, it should be, but it would be better to enforce it in a more reliable way.

**Comment by Glandos** [comment]
See https://github.com/MagicStack/uvloop/issues/95

**Comment by boramalper** [comment]
Closing as we no longer use Python (but switched to Go). Let me know if you encounter any other issues with more recent versions. =)
