### ISSUE TITLE
Update the documentation for iptables rule to prevent excessive EPERM (congestion) errors

### ISSUE THREAD

**Issue by boramalper** [boramalper/magnetico#95]
*\*phew\**, what a long title!

Since the very early days of its development, the spectre of EPERM (errno = 1) has been daunting **magnetico**, and it worsened as **magnetico** became lighter on computer and hence had more room to send *more packages per second*.

I found David Schwartz's answer to a user that was suffering from the same issue [on comp.protocols.tcp-ip newsgroup](http://www.archivum.info/comp.protocols.tcp-ip/2009-05/00128/Re-UDP-socket-amp-amp-sendto-amp-amp-EPERM.html) from 2009, which suggested it was due to congestion. I took it granted and implemented a "primitive" congestion control based on that.

Nevertheless, I just discovered today that it is indeed (or *may also*) caused by `iptables` on Linux. After reading [Eosis' question & reply on stackoverflow](https://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted), I checked my `/var/log/syslog` and it was indeed full of entries like this:

```
Jun 11 10:20:18 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
Jun 11 10:20:18 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
Jun 11 10:20:18 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
Jun 11 10:20:19 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
Jun 11 10:20:32 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
Jun 11 10:20:32 localhost kernel: nf_conntrack: nf_conntrack: table full, dropping packet
...
```

What Eosis suggested on stackoverflow worked perfectly and I didn't see any more EPERM after that:

```
# iptables -I OUTPUT -t raw -p udp --sport 5060 -j CT --notrack
# iptables -I PREROUTING -t raw -p udp --dport 5060 -j CT --notrack
```

I think (read *I guess*) that iptables was not fast enough to process vast amount of messages we were sending and unless you use `conntrack` extension of `iptables`, it can be (and should be) disabled to eliminate EPERM errors and increase performance.

__Hence:__

- [x] Check what the above commands **precisely** means, and alters.
- [x] Update the documentation accordingly.
   * Clearly indicating that those commands require root access.

**Comment by Glandos** [comment]
To simplify (a bit) commands, you can replace `-j CT --notrack` by `-j NOTRACK`.

And it really helps me to remove connection tracking for me.

**Comment by boramalper** [comment]
Done! See 45a2679. =)
